### ISSUE TITLE
Hello, can you share self-attention pooling code ? Please

### ISSUE THREAD

**Issue by taotao033** [bamtercelboo/pytorch_Joint-Word-Segmentation-and-POS-Tagging#5]

**Comment by dalinvip** [comment]
Sorry for that, Pytorch not write self-attention pooling code, you can refer to C++ code, [here](https://github.com/zhangmeishan/NNTranJSTagger/blob/master/EGN3LDG/Attention.h).

**Comment by taotao033** [comment]
Thanks a lot.
